import pygame, sys, os, pygame, pytmx, numpy as np
FPSGAME = 20


SEKUNDENZUG = 30
GAMELENGTH = 600
SEKUNDENPUNKTE = 15
POPANPASSENINTERVAL = 1 #soviele Frames pro populationAnpassen
# Modellfaktoren
TODFAKTOR = 0.005
TEMPANPASSKOEFF = 0.01 # Wie stark Temperaturanpassung sich auf die Fitness auswirkt
ANGRIFFHUNGER = 0.1
PFLANZENREGENERATION = 0.1
MAXPFLANZEN = 2
ANPASSUNGSEKUNDEN = 30
ANPASSUNGSCHANCE = 3

#Mutationenstats
GETFASTBONUS = 0.2
FITNESSBOOSTBONUS = 0.2
EVASIONBOOSTBONUS = 1
PRECISIONBOOSTBONUS = 1
INTBOOSTBONUS = 1
INTBOOSTMULT = 2
# Umwelkartenstats
DEADDUDESMETEOR = 5
HEATWAVEAMOUNT = 20
HEATWAVEDURATION = 60
COOLWAVEAMOUNT = 20
COOLWAVEDURATION = 60
