# Mutationenstats
GETFASTBONUS = 2
FITNESSBOOSTBONUS = 0.2
EVASIONBOOSTBONUS = 1
PRECISIONBOOSTBONUS = 1
INTBOOSTBONUS = 1
INTBOOSTMULT = 1 #Das heisst mal 2

STATSZUMUTIEREN = ["SPEED", "FITNESS", "EVASION", "PRECISION", "INTFLAT", "INTMULT"]

# Mutationen
getFast = {"SPEED": GETFASTBONUS}
getFitness = {"FITNESS": FITNESSBOOSTBONUS}
getEvasion = {"EVASION": EVASIONBOOSTBONUS}
getPrecision = {"PRECISION": PRECISIONBOOSTBONUS}
getInt = {"INTFLAT": INTBOOSTBONUS, "INTMULT": INTBOOSTMULT}
