HIGHMOUNTAIN = 0
SNOWYMOUNTAIN = 1
DESERT = 2
HILLS = 3
STEPPE = 4
RIVER = 5
FOREST = 6
RIVERBANK = 7
DIRT = 8
GREENFIELD = 9
FOREST1 = 10
LOWMOUNTAINS = 11
OCEAN = 12
COASTWATER = 13
BEACH = 14
COASTGRASS = 15

# terrainclasses
TERRAIN = {"hexagonal1": (RIVER, FOREST, RIVERBANK, DIRT, GREENFIELD),
           "berge": (HIGHMOUNTAIN, SNOWYMOUNTAIN), "grass": (DESERT, HILLS, STEPPE),
           "overworld": (FOREST1, LOWMOUNTAINS), "water": (OCEAN, ),
           "watergrasssand": (COASTWATER, BEACH, COASTGRASS)}

TEMP = {HIGHMOUNTAIN: 3, SNOWYMOUNTAIN: -10, DESERT: 40, HILLS: 20,
        STEPPE: 20, RIVER: 10, FOREST: 15, RIVERBANK: 15, DIRT: 20, GREENFIELD: 25,
        FOREST1: 18, LOWMOUNTAINS: 10, OCEAN: 3, COASTWATER: 15, BEACH: 25, COASTGRASS: 25}

SPEEDIN = {HIGHMOUNTAIN: 0.3, SNOWYMOUNTAIN: 0.1, DESERT: 0.8, HILLS: 0.5,
           STEPPE: 1, RIVER: 1, FOREST: 0.6, RIVERBANK: 0.9, DIRT: 1, GREENFIELD: 1,
           FOREST1: 0.7, LOWMOUNTAINS: 0.5, OCEAN: 2, COASTWATER: 1, BEACH: 0.8, COASTGRASS: 1}

SWIMIN = {HIGHMOUNTAIN: 0, SNOWYMOUNTAIN: 0, DESERT: 0, HILLS: 0,
          STEPPE: 0, RIVER: 1, FOREST: 0, RIVERBANK: 0, DIRT: 0, GREENFIELD: 0,
          FOREST1: 0, LOWMOUNTAINS: 0, OCEAN: 3, COASTWATER: 2, BEACH: 0, COASTGRASS: 0}

# relative Rate des pflanzenessen-wachstums

PLANTGROWTH = {HIGHMOUNTAIN: 0.3, SNOWYMOUNTAIN: 0.2, DESERT: 0.1, HILLS: 1,
               STEPPE: 0.8, RIVER: 1, FOREST: 2, RIVERBANK: 0.8, DIRT: 0.5, GREENFIELD: 1.3,
               FOREST1: 1.5, LOWMOUNTAINS: 0.8, OCEAN: 1, COASTWATER: 1.3, BEACH: 0.7, COASTGRASS: 1.1}
